# StarterPack Configuration for Docker/Development
# This file is used by Docker and development environments
# https://github.com/carmelosantana/minecraft-starter-pack

starter-pack:
  # Enable or disable the starter pack feature
  enabled: true
  
  # Broadcast welcome message to server when a player receives their starter pack
  broadcast: true
  
  # Welcome message sent to new players (supports color codes with &)
  # Placeholder: {player} - replaced with player name
  welcome-message: "&aWelcome to the server, &b{player}&a!"
  
  # Broadcast message sent to all players when someone receives their starter pack
  # Placeholder: {player} - replaced with player name
  broadcast-message: "&e{player} &7has joined the server for the first time!"

  # List of items to give to new players
  items:
    # Diamond Pickaxe with custom name, lore, and enchantments
    - material: DIAMOND_PICKAXE
      name: "&bStarter Pickaxe"
      lore:
        - "&7A durable tool to begin your journey"
        - "&7Unbreaking III, Efficiency II"
      enchantments:
        UNBREAKING: 3
        EFFICIENCY: 2
      amount: 1

    # Cooked Beef for food
    - material: COOKED_BEEF
      amount: 16

    # Custom Gluten-Free Bread with special properties
    - material: BREAD
      name: "&fGluten-Free Bread"
      lore:
        - "&7Healthier than wheat bread"
        - "&7Light and energizing"
        - "&aRestores extra hunger points"
      amount: 3

# Debug settings (for development)
debug:
  # Enable debug logging
  enabled: true
  
  # Log all player join events (even for existing players)
  log-all-joins: true
